services:
  orders_apps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_orders_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: orders_app
    ports:
      - '5433:5432'
    expose:
      - 5432
    volumes:
      - orders_app_volume:/var/lib/postgresql/data
volumes:
  orders_app_volume:
